import Head from "next/head";
import Title from "components/Title";
import { Container } from "components/Container";
import Image from "next/image";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title title="NextJS TypeScript Template" />
      <Image src="/vercel.svg" alt="vercel" width="100px" height="100px" />
    </Container>
  );
}
